# Site settings
title: Laboratório de Ecologia Humana
logo: /assets/images/logo_leh.png
email: lab.ecohumana.unisanta@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  populações humanas | ecossistemas | tecnologias

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://lab-eco-humana.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
remote_theme: pages-themes/slate
# theme: minima
# remote_theme: pages-themes/tactile@v0.2.0
plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
# plugins:
  - jekyll-feed

# Excerpt separator
# The default is ""
# To remove it, use the following:
excerpt_separator: ""

# Footer content
footer_content: "CC-BY {{ site.time | date: '%Y' }}. <a href='mailto:{{ site.email }}'>{{ site.email }}</a>"