# Site settings
title: Laboratório de Ecologia Humana
logo: /assets/images/header.png
email: lab.ecohumana.unisanta@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  populações humanas | ecossistemas | tecnologias

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://lab-eco-humana.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# i18n settings
lang: pt
languages: ["pt", "en"]

t:
  pt:
    description: "populações humanas | ecossistemas | tecnologias"
    footer:
      brand: "LabEcoHumana 2012- |"
      rights: "Alguns direitos reservados"
    nav:
      home: "Início"
      equipe: "Equipe"
      projetos: "Projetos"
      producoes: "Produções"
  en:
    description: "human populations | ecosystems | technologies"
    footer:
      brand: "LabEcoHumana 2012- |"
      rights: "Some rights reserved"
    nav:
      home: "Home"
      equipe: "Team"
      projetos: "Projects"
      producoes: "Publications"

collections:
  pt:
    output: true
    permalink: /:path/
  en:
    output: true
    permalink: /en/:path/

# Build settings
remote_theme: pages-themes/slate
# theme: minima
# remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Excerpt separator
# The default is ""
# To remove it, use the following:
excerpt_separator: ""

# Footer content
footer_content: "CC-BY {{ site.time | date: '%Y' }}. <a href='mailto:{{ site.email }}'>{{ site.email }}</a>"